// routes.js
// Keep route names in one place for navigation
export default {
  SPLASH: 'Splash',
  MAIN: 'Main',
  LOGIN: 'Login',
  OTP: 'OTP',
  DASHBOARD: 'Dashboard',
  ORDERS: 'Orders',
  ORDER_DETAILS: 'OrderDetails',
  NAVIGATION: 'Navigation',
  DELIVERY_CONFIRM: 'DeliveryConfirm',
  PROFILE: 'Profile',
  PERFORMANCE: 'Performance',
  NOTIFICATIONS: 'Notifications',
  SETTINGS: 'Settings',
  HELP: 'Help',
  LOGOUT_CONFIRM: 'LogoutConfirm',
  EARNINGS: 'Earnings',
  ATTENDANCE: 'Attendance',
  OFFLINE: 'Offline',
  CHANGE_PASSWORD: 'ChangePassword',
  SUPPORT: 'Support',
  FEEDBACK: 'Feedback',
  PROOF_UPLOAD: 'ProofUpload',
  OTP_VERIFICATION: 'OTPVerification',
  UPLOAD_DOCUMENTS: 'UploadDocuments',
  AVAILABLE_ORDERS: 'AvailableOrders',
  ORDER_HISTORY: undefined,
};
